### ISSUE TITLE
support any alphanumeric key

### ISSUE THREAD

**Issue by knausj85** [daanvdh/talonTextNavigation#4]
https://github.com/daanvdh/talonTextNavigation/blob/7dd8d17cf4fcc4a4976e48f3ba8c3a99c19ace17/src/text_navigation.talon#L4

I was thinking to add a new capture in keys.py to use here instead of just symbol_key

```
@mod.capture(rule="( <self.letter> | <self.number_key> | <self.symbol_key> )")
def any_alphanumeric_key(m) -> str:
    "any alphanumeric key"
    return str(m)
```

thoughts?

**Comment by pokey** [comment]
Yeah I like that idea

**Comment by daanvdh** [comment]
Yes, this nicer than what I currently implemented. I also wrote a implementation accepting any text. Do you think we should add that somehow to the capture, or do you think this should be a separate talon statement?

**Comment by knausj85** [comment]
I’ll take a peek at your latest when my power is back 🙃

I generally prefer separate statements to reduce obfuscation / ease
customization.

I went ahead and submitted this new capture yesterday FYI
